version: "2"
services:
  dse:
    image: "crwstax/graph-book:0.0.1"
    command: -s -k -g
    environment:
      - DS_LICENSE=accept
    ports:
      - 9042:9042
      - 8182:8182
  studio:
    image: "crwstax/graph-book-studio:0.0.1"
    environment:
      - DS_LICENSE=accept
      - STUDIO_DEFAULT_CONNECTION_HOST=host.docker.internal
      - STUDIO_DEFAULT_CONNECTION_NAME=Docker
    ports:
      - 9091:9091
    depends_on:
      - dse

#  datastax:
#    image: "amazonlinux"
#    container_name: datastax_enterprise
#    build:
#      context: ./
#      dockerfile: datastaxenterprise.dockerfile
#    ports:
#      - 9042:9042
#      - 8182:8182
#      - 9091:9091
#    volumes:
#      - /Users/senguptag/Development/datastax:/mnt/datastax/
#    command: bash -c "
#                JAVA_HOME=/mnt/datastax/amazon-corretto-8.265.01.1-linux-x64/ /mnt/datastax/dse-6.8.3/bin/dse cassandra -s -g -k -R \
#                && JAVA_HOME=/mnt/datastax/amazon-corretto-8.265.01.1-linux-x64/ /mnt/datastax/datastax-studio-6.8.2/bin/server.sh
#            "